export const allItems = [
    { "name": "Frozen Custard (chocolate)", "imgUrl": "frozen-custard-chocolate", "category": "frozen", "price": 6.50 },
    { "name": "Lemon Cake", "imgUrl": "lemon-cake", "category": "cake", "price": 24.00 },
    { "name": "Biscotti (almond)", "imgUrl": "biscotti-almond", "category": "cookie", "price": 2.50 },
    { "name": "Red Velvet Cake", "imgUrl": "red-velvet-cake", "category": "cake", "price": 28.00 },
    { "name": "Chocolate Cake", "imgUrl": "chocolate-cake", "category": "cake", "price": 25.00 },
    { "name": "Sponge Cake", "imgUrl": "sponge-cake", "category": "cake", "price": 21.00 },
    { "name": "Coffee Cake", "imgUrl": "coffee-cake", "category": "cake", "price": 20.00 },
    { "name": "Carrot Cake", "imgUrl": "carrot-cake", "category": "cake", "price": 26.00 },
    { "name": "Chocolate Tart", "imgUrl": "chocolate-tart", "category": "pastry", "price": 17.50 },
    { "name": "Pound Cake", "imgUrl": "pound-cake", "category": "cake", "price": 18.50 },
    { "name": "Anzac Biscuits", "imgUrl": "anzac-biscuits", "category": "cookie", "price": 2.00 },
    { "name": "Marble Cake", "imgUrl": "marble-cake", "category": "cake", "price": 23.00 },
    { "name": "Black Forest Cake", "imgUrl": "black-forest-cake", "category": "cake", "price": 32.00 },
    { "name": "Bundt Cake", "imgUrl": "bundt-cake", "category": "cake", "price": 27.00 },
    { "name": "Cupcakes (chocolate)", "imgUrl": "cupcakes-chocolate", "category": "cake", "price": 3.50 },
    { "name": "Ice Cream Cake (chocolate vanilla)", "imgUrl": "ice-cream-cake-chocolate-vanilla", "category": "frozen", "price": 35.00 },
    { "name": "Frozen Yogurt (berry)", "imgUrl": "frozen-yogurt-berry", "category": "frozen", "price": 5.50 },
    { "name": "Ice Pops (strawberry)", "imgUrl": "ice-pops-strawberry", "category": "frozen", "price": 2.50 },
    { "name": "Paletas (watermelon)", "imgUrl": "paletas-watermelon", "category": "frozen", "price": 3.00 },
    { "name": "Semifreddo (almond)", "imgUrl": "semifreddo-almond", "category": "frozen", "price": 7.00 },
    { "name": "Bingsu (red bean)", "imgUrl": "bingsu-red-bean", "category": "frozen", "price": 8.00 },
    { "name": "Ice Cream (vanilla)", "imgUrl": "ice-cream-vanilla", "category": "frozen", "price": 5.00 },
    { "name": "Granita (lemon)", "imgUrl": "granita-lemon", "category": "frozen", "price": 3.50 },
    { "name": "Sherbet (orange)", "imgUrl": "sherbet-orange", "category": "frozen", "price": 4.00 },
    { "name": "Lemon Mousse", "imgUrl": "lemon-mousse", "category": "pudding", "price": 5.75 },
    { "name": "Gelato (pistachio)", "imgUrl": "gelato-pistachio", "category": "frozen", "price": 6.00 },
    { "name": "Dondurma (vanilla)", "imgUrl": "dondurma-vanilla", "category": "frozen", "price": 7.50 },
    { "name": "Fruit Cake", "imgUrl": "fruit-cake", "category": "cake", "price": 30.00 },
    { "name": "Scones (blueberry)", "imgUrl": "scones-blueberry", "category": "pastry", "price": 3.50 },
    { "name": "Lemon Meringue Pie", "imgUrl": "lemon-meringue-pie", "category": "pastry", "price": 21.00 },
    { "name": "Clafoutis (cherry)", "imgUrl": "clafoutis-cherry", "category": "fruit", "price": 11.00 },
    { "name": "Cream Puffs", "imgUrl": "cream-puffs", "category": "pastry", "price": 4.00 },
    { "name": "Tapioca Pudding", "imgUrl": "tapioca-pudding", "category": "pudding", "price": 4.25 },
    { "name": "Chocolate Mousse", "imgUrl": "chocolate-mousse", "category": "pudding", "price": 6.00 },
    { "name": "Rice Pudding", "imgUrl": "rice-pudding", "category": "pudding", "price": 4.75 },
    { "name": "Apple Pie", "imgUrl": "apple-pie", "category": "pastry", "price": 18.00 },
    { "name": "Danish (cherry)", "imgUrl": "danish-cherry", "category": "pastry", "price": 4.50 },
    { "name": "Baklava", "imgUrl": "baklava", "category": "pastry", "price": 7.00 },
    { "name": "Cherry Pie", "imgUrl": "cherry-pie", "category": "pastry", "price": 20.00 },
    { "name": "Custard Tart", "imgUrl": "custard-tart", "category": "pastry", "price": 15.00 },
    { "name": "Éclairs (chocolate)", "imgUrl": "eclairs-chocolate", "category": "pastry", "price": 5.00 },
    { "name": "Mille-feuille", "imgUrl": "mille-feuille", "category": "pastry", "price": 6.50 },
    { "name": "Pumpkin Pie", "imgUrl": "pumpkin-pie", "category": "pastry", "price": 19.00 },
    { "name": "Banana Split", "imgUrl": "banana-split", "category": "fruit", "price": 9.50 },
    { "name": "Croissants (almond)", "imgUrl": "croissants-almond", "category": "pastry", "price": 4.00 },
    { "name": "Fruit Crumble (peach)", "imgUrl": "fruit-crumble-peach", "category": "fruit", "price": 8.00 },
    { "name": "Tres Leches Cake", "imgUrl": "tres-leches-cake", "category": "cake", "price": 29.00 },
    { "name": "Vanilla Cake", "imgUrl": "vanilla-cake", "category": "cake", "price": 22.50 },
    { "name": "Strawberry Mousse", "imgUrl": "strawberry-mousse", "category": "pudding", "price": 5.50 },
    { "name": "Butterscotch Pudding", "imgUrl": "butterscotch-pudding", "category": "pudding", "price": 4.50 },
    { "name": "Blancmange", "imgUrl": "blancmange", "category": "pudding", "price": 5.00 },
    { "name": "Fudgy Brownies", "imgUrl": "fudgy-brownies", "category": "cookie", "price": 3.00 },
    { "name": "Berry Cobbler", "imgUrl": "berry-cobbler", "category": "fruit", "price": 8.00 },
    { "name": "Vanilla Pudding", "imgUrl": "vanilla-pudding", "category": "pudding", "price": 4.00 },
    { "name": "Zabaglione", "imgUrl": "zabaglione", "category": "pudding", "price": 8.00 },
    { "name": "Shortbread Cookies", "imgUrl": "shortbread-cookies", "category": "cookie", "price": 2.25 },
    { "name": "Nanaimo Bars", "imgUrl": "nanaimo-bars", "category": "cookie", "price": 3.75 },
    { "name": "Sorbet (raspberry)", "imgUrl": "sorbet-raspberry", "category": "frozen", "price": 4.50 },
    { "name": "Mango Sticky Rice", "imgUrl": "mango-sticky-rice", "category": "fruit", "price": 9.00 },
    { "name": "Mochi Ice Cream (mango)", "imgUrl": "mochi-ice-cream-mango", "category": "frozen", "price": 4.00 },
    { "name": "Fruit Salad", "imgUrl": "fruit-salad", "category": "fruit", "price": 6.00 },
    { "name": "Peanut Butter Cookies", "imgUrl": "peanut-butter-cookies", "category": "cookie", "price": 1.80 },
    { "name": "Lemon Bars", "imgUrl": "lemon-bars", "category": "cookie", "price": 3.25 },
    { "name": "Oatmeal Raisin Cookies", "imgUrl": "oatmeal-raisin-cookies", "category": "cookie", "price": 1.75 },
    { "name": "Chocolate Chip Cookies", "imgUrl": "chocolate-chip-cookies", "category": "cookie", "price": 2.00 },
    { "name": "Sugar Cookies", "imgUrl": "sugar-cookies", "category": "cookie", "price": 1.50 },
    { "name": "Blondies", "imgUrl": "blondies", "category": "cookie", "price": 2.80 },
    { "name": "Seven-Layer Bars", "imgUrl": "seven-layer-bars", "category": "cookie", "price": 3.50 },
    { "name": "Crème Caramel", "imgUrl": "creme-caramel", "category": "pudding", "price": 6.50 },
    { "name": "Madeleines", "imgUrl": "madeleines", "category": "cookie", "price": 2.75 },
    { "name": "Pecan Pie", "imgUrl": "pecan-pie", "category": "pastry", "price": 22.00 },
    { "name": "Es Buah", "imgUrl": "es-buah", "category": "fruit", "price": 7.50 },
    { "name": "Strawberry Shortcake", "imgUrl": "strawberry-shortcake", "category": "fruit", "price": 8.50 },
    { "name": "Baked Apples", "imgUrl": "baked-apples", "category": "fruit", "price": 6.50 },
    { "name": "Fruit Pizza", "imgUrl": "fruit-pizza", "category": "fruit", "price": 12.00 },
    { "name": "Crème brûlée", "imgUrl": "creme-brulee", "category": "pudding", "price": 7.00 },
    { "name": "Panna Cotta (berry)", "imgUrl": "panna-cotta-berry", "category": "pudding", "price": 6.25 },
    { "name": "Pot de Crème (chocolate)", "imgUrl": "pot-de-creme-chocolate", "category": "pudding", "price": 7.50 },
    { "name": "Macarons (assorted)", "imgUrl": "macarons-assorted", "category": "cookie", "price": 4.00 },
    { "name": "Gingerbread Cookies", "imgUrl": "gingerbread-cookies", "category": "cookie", "price": 2.20 },
    { "name": "Grilled Pineapple with Coconut Ice Cream", "imgUrl": "grilled-pineapple-with-coconut-ice-cream", "category": "fruit", "price": 10.00 },
    { "name": "Poached Pears", "imgUrl": "poached-pears", "category": "fruit", "price": 9.00 },
    { "name": "Apple Crisp", "imgUrl": "apple-crisp", "category": "fruit", "price": 7.50 },
    { "name": "Eton Mess", "imgUrl": "eton-mess", "category": "fruit", "price": 7.00 },
    { "name": "Tarte Tatin (apple)", "imgUrl": "tarte-tatin-apple", "category": "fruit", "price": 10.50 },
    { "name": "Fruit Tart (berry)", "imgUrl": "fruit-tart-berry", "category": "pastry", "price": 16.00 }
]